sudo: false
language: node_js
os: linux

install:
  - cd $TRAVIS_BUILD_DIR/client && yarn
  - cd $TRAVIS_BUILD_DIR/functions && yarn
notifications:
  email: false
cache:
  directories:
    - $HOME/.yarn-cache
    - node_modules
before_script:
  - pwd
  - cd $TRAVIS_BUILD_DIR/client && yarn test:ci
script:
  - pwd
  - cd $TRAVIS_BUILD_DIR/client && NODE_ENV=production yarn build
after_success:
  - CODECLIMATE_REPO_TOKEN=$CODECLIMATE_REPO_TOKEN npx codeclimate-test-reporter < $TRAVIS_BUILD_DIR/client/coverage/lcov.info
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: "$FIREBASE_TOKEN"
  on:
    tags: true
after_deploy:
  - cd $TRAVIS_BUILD_DIR/client && yarn add slack-notify shelljs && node ./bin/notify-slack.js