sudo: false
language: node_js
os: linux
env:
  - CLIENT_DIR=$TRAVIS_BUILD_DIR/client
  - FUNCTIONS_DIR=$TRAVIS_BUILD_DIR/functions
install:
  - cd $CLIENT_DIR && yarn
  - cd $FUNCTIONS_DIR && yarn
notifications:
  email: false
cache:
  directories:
    - $HOME/.yarn-cache
    - node_modules
before_script:
  - pwd
  - cd $CLIENT_DIR && yarn test:ci
script:
  - pwd
  - cd $CLIENT_DIR && NODE_ENV=production yarn build
after_success:
  - CODECLIMATE_REPO_TOKEN=$CODECLIMATE_REPO_TOKEN npx codeclimate-test-reporter < $CLIENT_DIR/coverage/lcov.info
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: "$FIREBASE_TOKEN"
  on:
    tags: true
after_deploy:
  - cd $CLIENT_DIR && yarn add slack-notify shelljs && node ./bin/notify-slack.js