sudo: false
language: node_js
os: linux
env:
  global:
    - CLIENT_PATH=$HOME/client
install:
  - cd $CLIENT_PATH && yarn
notifications:
  email: false
branches:
  only:
    - master
cache:
  directories:
    - $CLIENT_PATH/.yarn-cache
    - $CLIENT_PATH/node_modules
before_script:
  - cd $CLIENT_PATH && yarn test:ci
script:
  - cd $CLIENT_PATH && NODE_ENV=production yarn build
after_success:
  - CODECLIMATE_REPO_TOKEN=$CODECLIMATE_REPO_TOKEN npx codeclimate-test-reporter < $CLIENT_PATHx/coverage/lcov.info
