sudo: false
language: node_js
os: linux
install:
  - yarn
notifications:
  email: false
node_js:
  - '8.9.4'
script:
  - yarn build
  - yarn test:ci
branches:
  only:
    - master
cache:
  yarn: true
  directories:
    - $HOME/.yarn-cache
    - node_modules
addons:
  code_climate:
    repo_token: $CODECLIMATE_REPO_TOKEN
after_script:
  - npx codeclimate-test-reporter < ./coverage/lcov.info
