sudo: false
language: node_js
os: linux
install:
  - yarn
notifications:
  email: false
cache:
  directories:
    - $HOME/.yarn-cache
    - node_modules
#before_script:
#  - yarn test:ci
script:
  - NODE_ENV=production yarn build
#after_success:
#  - CODECLIMATE_REPO_TOKEN=$CODECLIMATE_REPO_TOKEN npx codeclimate-test-reporter < ./coverage/lcov.info
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: "$FIREBASE_TOKEN"
  on:
    tags: true
after_deploy:
  - yarn add slack-notify shelljs && node ./bin/notify-slack.js
