sudo: false
language: node_js
os: linux
install:
  - cd $HOME/client && yarn
notifications:
  email: false
branches:
  only:
    - master
cache:
  directories:
    - $HOME/client/.yarn-cache
    - $HOME/client/node_modules
before_script:
  - cd $HOME/client && yarn test:ci
script:
  - cd $HOME/client && NODE_ENV=production yarn build
after_success:
  - CODECLIMATE_REPO_TOKEN=$CODECLIMATE_REPO_TOKEN npx codeclimate-test-reporter < $HOME/clientx/coverage/lcov.info
