sudo: false
language: node_js
os: linux
install:
  - yarn
notifications:
  email: false
node_js:
  - '8.9.4'
branches:
  only:
    - master
cache:
  yarn: true
  directories:
    - $HOME/.yarn-cache
    - node_modules
script:
  - yarn build
  - yarn test:ci
after_script:
  - CODECLIMATE_REPO_TOKEN=$CODECLIMATE_REPO_TOKEN npx codeclimate-test-reporter < ./coverage/lcov.info
