version: '2'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    expose:
      - 3001
    volumes:
      - ./server:/usr/src/server

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.client
    environment:
      - PORT=8080
    ports:
      - "8080:8080"
    volumes:
      - ./client/src:/usr/src/app/src
    depends_on:
      - server